version: 2
jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - run:
          name: Test
          command: |
            . venv/bin/activate
            python3 -m unittest discover

      - run:
          name: Lint
          command: |
            . venv/bin/activate
            pylint --output-format parseable --disable C0111,R0205 notion tests
